<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>1591</NoWarn>
    <UserSecretsId>a838757b-fa67-41de-bd5a-3a41a1de5793</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.18" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.17">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventService.Application\EventService.Application.csproj" />
    <ProjectReference Include="..\EventService.Infrastructure\EventService.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="EventManager.Common.AspNetCore">
      <HintPath>..\..\Common\EventManager.Common.AspNetCore\bin\Release\net9.0\EventManager.Common.AspNetCore.dll</HintPath>
    </Reference>
    <Reference Include="EventManager.Common.Core">
      <HintPath>..\..\Common\EventManager.Common.AspNetCore\bin\Release\net9.0\EventManager.Common.Core.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
