<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="EventManager.Common.Core">
      <HintPath>..\..\Common\EventManager.Common.Core\bin\Release\net9.0\EventManager.Common.Core.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
