<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BookingService.Domain\BookingService.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="EventManager.Common.Core">
      <HintPath>..\..\Common\EventManager.Common.AspNetCore\bin\Release\net9.0\EventManager.Common.Core.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
