<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\**" />
    <Compile Remove="Infrastructure\Interfaces\**" />
    <Content Remove="Controllers\**" />
    <Content Remove="Infrastructure\Interfaces\**" />
    <EmbeddedResource Remove="Controllers\**" />
    <EmbeddedResource Remove="Infrastructure\Interfaces\**" />
    <None Remove="Controllers\**" />
    <None Remove="Infrastructure\Interfaces\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventManager.Application\EventManager.Application.csproj" />
    <ProjectReference Include="..\EventManager.Infrastructure\EventManager.Infrastructure.csproj" />
  </ItemGroup>

</Project>
